### ISSUE TITLE
Тестовое задание на позицию разработчика биоинформатического ПО

### ISSUE THREAD

**Issue by m-a-k-s-i-m** [biocad/career#8]
Здравствуйте.

Небольшое уточнение. В тестовом задании https://github.com/biocad/career/blob/master/tests/bioinf-dev.md не указано какой коэффициент Fij использовать в случае, когда не существует цепочки связей между атомами i и j. У вас, судя по результату, для таких случаев Fij принимался равным 1. Но, если такие пары атомов игнорировать (исходя из описания "Fij = 0, если атомы разделены меньше, чем тремя связязми"), результат будет несколько другим (-64055.3). Во избежание разночтений, видимо имеет смысл прописать этот случай явно.

Спасибо.

**Comment by PianeRamso** [comment]
Привет! 

Если атомы не связаны, надо считать Fij = 1. Описание обновили. Спасибо.
